version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build: .
    command: python3 main.py
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://your_username:your_password@db:5432/your_database

volumes:
  postgres_data: